feat: Added Entity Framework Core's schemas (#6)
* feat: Added (painful) EFC auto-generated schemas

They need clean-up, seriously.

* cleanup: First step at cleaning everything up

* build: Resolved build errors

* cleanup: Move entities to their own files for organization

* fix: Resolved complex type problem

Next problem:

System.InvalidOperationException: The child/dependent side could not be determined for the one-to-one relationship between 'GuildAutoModeration.Attachment' and 'GuildModerationAttachment.Guild'. To identify the child/dependent side of the relationship, configure the foreign key property. If these navigations should not be part of the same relationship configure them without specifying the inverse. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.

* fix: Remove testing code

* cleanup: Move classes to their respective files

Current error:

System.InvalidOperationException: The entity type 'GuildActionTrigger' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.

* cleanup: Seal all model classes, refactor Guild.Actions

* fix: Resolved the last bug, EFC is now working!

* misc: Added lots of docs and fixed Roslyn suggestions

* refactor: Revamp GuildRoles table

* cleanup: Converted the last class to a struct

* fix: Resolved all build warnings

* cleanup: Optimize SQL tables, reduce the amount of indexes drastically

* misc: Updated more names, turned GuildModerationSoftAction into a struct

* feat: Added setters to GuildModerationSoftAction

* refactor: Use flag enum instead

* docs: Finished writing docs and entities