cleanup: Move classes to their respective files
Current error:

System.InvalidOperationException: The entity type 'GuildActionTrigger' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.